// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzc7xU02Kg0L0MLEbnv0o2i-fNgvVzr8',
    appId: '1:845530294110:web:38631e5a63f28f38bc91cf',
    messagingSenderId: '845530294110',
    projectId: 'safeher-b1e3c',
    authDomain: 'safeher-b1e3c.firebaseapp.com',
    storageBucket: 'safeher-b1e3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_D_sdhMz88ao9c-VvrWpN1J8chG0Gjww',
    appId: '1:845530294110:android:f6fb557cc6e2680abc91cf',
    messagingSenderId: '845530294110',
    projectId: 'safeher-b1e3c',
    storageBucket: 'safeher-b1e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAARPG5Mcxo6nEgl1khM1YQtBHO2uA-tVs',
    appId: '1:845530294110:ios:84803f301225cedcbc91cf',
    messagingSenderId: '845530294110',
    projectId: 'safeher-b1e3c',
    storageBucket: 'safeher-b1e3c.appspot.com',
    androidClientId: '845530294110-79umfqb1g727atdt6frpotdpgft2htco.apps.googleusercontent.com',
    iosClientId: '845530294110-uoppq34p922cf9u4gt1odq1p68btb891.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeher3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAARPG5Mcxo6nEgl1khM1YQtBHO2uA-tVs',
    appId: '1:845530294110:ios:1bfd1811a6a6df8fbc91cf',
    messagingSenderId: '845530294110',
    projectId: 'safeher-b1e3c',
    storageBucket: 'safeher-b1e3c.appspot.com',
    androidClientId: '845530294110-79umfqb1g727atdt6frpotdpgft2htco.apps.googleusercontent.com',
    iosClientId: '845530294110-gqjs3gca3i0mgkradbbq3dhrs69qsodc.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeher3.RunnerTests',
  );
}
